services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db

    ports:
      - 5432:5432
  
  s3_localstack:
    image: localstack/localstack:latest
    ports: 
      - 4566:4566
    environment: 
      - AWS_ACCESS_KEY_ID=chat_app
      - AWS_SECRET_ACCESS_KEY=chat_app
      - AWS_DEFAULT_REGION=ap-south-1

  redis:
    image: redis:8.4.0-alpine
    restart: always
    ports:
      - "6379:6379"